### ISSUE TITLE
Issues with TeamCity 9.1.X

### ISSUE THREAD

**Issue by DVGeoffrey** [cloudnative/teamcity-webhooks#2]
Not seeing webhooks since a few days after our TeamCity upgrade (not sure why it didn't stop working right away).  Errors I'm finding in the logs:

```
[2016-01-13 11:34:36,637]  ERROR -   jetbrains.buildServer.SERVER - WebHooks plugin - Failed to listen on buildFinished() of 'Integration Tests :: Fitnesse Build' #5.5.17878.45308 
java.lang.NullPointerException
    at io.cloudnative.teamcity.WebhooksListener.buildPayload(WebhooksListener.java:67)
    at io.cloudnative.teamcity.WebhooksListener.buildFinished(WebhooksListener.java:43)
    at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:120)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.superDispatch(ServerSideEventDispatcher.java:8)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher$1.run(ServerSideEventDispatcher.java:1)
    at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:24)
    at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAsSystem(SecurityContextImpl.java:17)
    at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.dispatch(ServerSideEventDispatcher.java:16)
    at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:67)
    at com.sun.proxy.$Proxy19.buildFinished(Unknown Source)
    at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl.finishBuild(RunningBuildsManagerImpl.java:198)
    at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl$1$1.run(RunningBuildsManagerImpl.java:1)
    at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
    at jetbrains.buildServer.serverSide.impl.RunningBuildsManagerImpl$1.run(RunningBuildsManagerImpl.java:1)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

We're running TeamCity Enterprise 9.1.5 (build 37377).

**Comment by DVGeoffrey** [comment]
D'oh!  This is the same issue as last time (https://github.com/cloudnative/teamcity-webhooks/issues/1).  I removed the dummy GIT repo I put in, forgetting its needed as a workaround.  Added it back and it's working.

**Comment by moinois** [comment]
I just downloaded and installed the webhooks TeamCity addin and I'm having the same issue. I thought it would have been fixed by now?
How did you create the dummy Git repo? Do you actually have a Git repo or is there a way to fool TeamCity to accept a nonsense uri?

**Comment by DVGeoffrey** [comment]
I created an actual Git repo which TeamCity could access.  Had to make sure it was the first repo in the list too.  Needed to delete an SVN repo from the buildType, add the Git repo and then add the SVN repo back.
